[project]
name = "BioHazardLocker"
version = "1.0.0"
authors = [{ name = "BioHazardAlBatros" }]
description = "Collection of mini-mods, mostly QoL."

[tool.sdkmod]
name = "BioHazard's Locker"
mod_type = "Standard" # or "Library"
supported_games = ["BL1","BL1E"]
coop_support = "Unknown"
auto_enable = "False"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }