[project]
name = "ColorEnhancer"
version = "1.0.1"
authors = [{ name = "BioHazardAlBatros" }]
description = "Removes desaturation and improves color grading.\n[Enhanced Only]: Only colors are boosted"

[tool.sdkmod]
name = "Color Enhancer"
mod_type = "Standard"
supported_games = ["BL1","BL1E"]
coop_support = "ClientSide"
auto_enable = true
download = "https://github.com/BioHazardAlBatros/BioHazard-BL1-SDK-Mods/raw/refs/heads/master/Color%20Enhancer/ColorEnhancer.sdkmod"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
